//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portfolio.Client.ResourceLanguage {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("portfolio.Client.ResourceLanguage.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Y/O Descargar CV.
        /// </summary>
        public static string AboutMe_ButtonDownloadCV {
            get {
                return ResourceManager.GetString("AboutMe.ButtonDownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Me gusta todo lo que tiene que ver con desarrollos ya sean web o escritorio. Soy una persona responsable y comprometida con mi trabajo, constantemente siempre estoy aprendiendo todo tipo de nuevas tecnologias y herramientas para que mis habilidades mejoren.
        ///
        ///Puedes ver algunos de mis proyectos realizados en la seccion de portafolio..
        /// </summary>
        public static string AboutMe_Content {
            get {
                return ResourceManager.GetString("AboutMe.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pais/Ciudad.
        /// </summary>
        public static string AboutMe_Country {
            get {
                return ResourceManager.GetString("AboutMe.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha De Nacimiento.
        /// </summary>
        public static string AboutMe_DateOfBirth {
            get {
                return ResourceManager.GetString("AboutMe.DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autos.
        /// </summary>
        public static string AboutMe_DivCars {
            get {
                return ResourceManager.GetString("AboutMe.DivCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo.
        /// </summary>
        public static string AboutMe_DivDev {
            get {
                return ResourceManager.GetString("AboutMe.DivDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juegos.
        /// </summary>
        public static string AboutMe_DivGames {
            get {
                return ResourceManager.GetString("AboutMe.DivGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Musica.
        /// </summary>
        public static string AboutMe_DivMusic {
            get {
                return ResourceManager.GetString("AboutMe.DivMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deportes.
        /// </summary>
        public static string AboutMe_DivSports {
            get {
                return ResourceManager.GetString("AboutMe.DivSports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Viajar.
        /// </summary>
        public static string AboutMe_DivTravel {
            get {
                return ResourceManager.GetString("AboutMe.DivTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string AboutMe_Email {
            get {
                return ResourceManager.GetString("AboutMe.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intereses.
        /// </summary>
        public static string AboutMe_interests {
            get {
                return ResourceManager.GetString("AboutMe.interests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola, soy Juan Manuel Ramirez Hernandez..
        /// </summary>
        public static string AboutMe_Name {
            get {
                return ResourceManager.GetString("AboutMe.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string AboutMe_PersonalInformation {
            get {
                return ResourceManager.GetString("AboutMe.PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        public static string AboutMe_Phone {
            get {
                return ResourceManager.GetString("AboutMe.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOBRE MI.
        /// </summary>
        public static string AboutMe_Title {
            get {
                return ResourceManager.GetString("AboutMe.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTÁCTAME!.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTE SITIO ESTA DESARROLLADO CON:.
        /// </summary>
        public static string Contact_WebSite {
            get {
                return ResourceManager.GetString("Contact.WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curriculum.
        /// </summary>
        public static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificado.
        /// </summary>
        public static string Curriculum_BtnCertificate {
            get {
                return ResourceManager.GetString("Curriculum.BtnCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Educacion.
        /// </summary>
        public static string Curriculum_Education {
            get {
                return ResourceManager.GetString("Curriculum.Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programando en Blazor - ASP.NET Core.
        /// </summary>
        public static string Curriculum_EducationBlazor_ASP_NETCore {
            get {
                return ResourceManager.GetString("Curriculum.EducationBlazor-ASP.NETCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APLICACION DEL MARCO DE TRABAJO SCRUM PARA PROYECTOS DE DESARROLLO DE SOFTWARE.
        /// </summary>
        public static string Curriculum_EducationScrum {
            get {
                return ResourceManager.GetString("Curriculum.EducationScrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TECNÓLOGO EN ANÁLISIS Y DESARROLLO DE SISTEMAS DE INFORMACIÓN.
        /// </summary>
        public static string Curriculum_EducationTecnologo {
            get {
                return ResourceManager.GetString("Curriculum.EducationTecnologo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas.
        /// </summary>
        public static string Curriculum_Hours {
            get {
                return ResourceManager.GetString("Curriculum.Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURRICULUM.
        /// </summary>
        public static string Curriculum_Title {
            get {
                return ResourceManager.GetString("Curriculum.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experiencia De Trabajo.
        /// </summary>
        public static string Curriculum_WorkExperience {
            get {
                return ResourceManager.GetString("Curriculum.WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de distintos formularios/componentes para proyectos web realizados en los siguientes lenguajes, Frameworks y librerías:.
        /// </summary>
        public static string Curriculum_WorkExperienceEmCartago {
            get {
                return ResourceManager.GetString("Curriculum.WorkExperienceEmCartago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollo de formularios/componentes para proyectos en visual studio escritorio realizados en los siguientes lenguajes, Frameworks y librerías:.
        /// </summary>
        public static string Curriculum_WorkExperiencePesajeInteligente {
            get {
                return ResourceManager.GetString("Curriculum.WorkExperiencePesajeInteligente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilidades.
        /// </summary>
        public static string Habilidades {
            get {
                return ResourceManager.GetString("Habilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollador de Software.
        /// </summary>
        public static string Index_Desarrollador {
            get {
                return ResourceManager.GetString("Index.Desarrollador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portafolio.
        /// </summary>
        public static string Portafolio {
            get {
                return ResourceManager.GetString("Portafolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portafolio.
        /// </summary>
        public static string Portfolio_Tilte {
            get {
                return ResourceManager.GetString("Portfolio.Tilte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRAMEWORKS Y LIBRERÍAS.
        /// </summary>
        public static string Skills_Bookstores {
            get {
                return ResourceManager.GetString("Skills.Bookstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LENGUAJES DE PROGRAMACION.
        /// </summary>
        public static string Skills_Languages {
            get {
                return ResourceManager.GetString("Skills.Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OTRAS HABILIDADES.
        /// </summary>
        public static string Skills_OtherSkills {
            get {
                return ResourceManager.GetString("Skills.OtherSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HABILIDADES PROFESIONALES.
        /// </summary>
        public static string Skills_ProfessionalSkills {
            get {
                return ResourceManager.GetString("Skills.ProfessionalSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HABILIDADES.
        /// </summary>
        public static string Skills_Title {
            get {
                return ResourceManager.GetString("Skills.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOFTWARE Y HERRAMIENTAS.
        /// </summary>
        public static string Skills_Tools {
            get {
                return ResourceManager.GetString("Skills.Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre Mi.
        /// </summary>
        public static string Sobre_Mi {
            get {
                return ResourceManager.GetString("Sobre Mi", resourceCulture);
            }
        }
    }
}
